import type { Hero, Skill } from "../types";

// 六位內建英雄與招式的種子資料（視覺資料在 pixelHeroes.ts）。阿光免費作為初始英雄，
// 其餘 5 位可在英雄商店用點數購買，價格為建議預設值，家長之後可在商店管理調整。
export const CORE_SKILLS: Skill[] = [
  {
    id: "skill-genki-slash",
    name: "元氣斬！",
    effectColor: "#F1C40F",
    animationType: "slash",
    particleShape: "star",
    unlockCost: 0,
    packId: "core",
  },
  {
    id: "skill-caramel-shuriken",
    name: "焦糖手裡劍！",
    effectColor: "#F4A261",
    animationType: "throw",
    particleShape: "bubble",
    unlockCost: 0,
    packId: "core",
  },
  {
    id: "skill-meteor-wish",
    name: "流星許願擊！",
    effectColor: "#9B5DE5",
    animationType: "magic",
    particleShape: "heart",
    unlockCost: 0,
    packId: "core",
  },
  {
    id: "skill-rocket-punch",
    name: "火箭飛拳！",
    effectColor: "#4EA8DE",
    animationType: "punch",
    particleShape: "bolt",
    unlockCost: 0,
    packId: "core",
  },
  {
    id: "skill-bubble-breath",
    name: "泡泡龍息！",
    effectColor: "#52B788",
    animationType: "beam",
    particleShape: "bubble",
    unlockCost: 0,
    packId: "core",
  },
  {
    id: "skill-paw-flurry",
    name: "肉球連打！",
    effectColor: "#D62828",
    animationType: "punch",
    particleShape: "heart",
    unlockCost: 0,
    packId: "core",
  },
  // ---------- 英雄商店擴充包（見 MAPLE_UI_GUIDE.md）----------
  {
    id: "skill-shadow-shred",
    name: "影襲割裂斬！",
    effectColor: "#1fd1ff",
    animationType: "slash",
    particleShape: "bolt",
    unlockCost: 0,
    packId: "core",
    burstText: "SHRED!",
  },
  {
    id: "skill-bamboo-fists",
    name: "竹林百裂拳！",
    effectColor: "#52B788",
    animationType: "punch",
    particleShape: "leaf",
    unlockCost: 0,
    packId: "core",
  },
  {
    id: "skill-symphony-blade",
    name: "音波聖劍破！",
    effectColor: "#F15BB5",
    animationType: "magic",
    particleShape: "note",
    unlockCost: 0,
    packId: "core",
  },
  {
    id: "skill-yuzu-cannon",
    name: "柚子極限轟炸！",
    effectColor: "#39d353",
    animationType: "beam",
    particleShape: "boom",
    unlockCost: 0,
    packId: "core",
    burstText: "BOOM!",
  },
  {
    id: "skill-star-dragon",
    name: "星海狂龍破！",
    effectColor: "#9b5dff",
    animationType: "slash",
    particleShape: "star",
    unlockCost: 0,
    packId: "core",
  },
];

export const CORE_HEROES: Hero[] = [
  {
    id: "hero-aguang",
    name: "小勇者阿光",
    avatar: "hero-aguang",
    price: 0,
    skillIds: ["skill-genki-slash"],
    defaultSkillId: "skill-genki-slash",
    packId: "core",
  },
  {
    id: "hero-pudding-ninja",
    name: "布丁忍者",
    avatar: "hero-pudding-ninja",
    price: 40,
    skillIds: ["skill-caramel-shuriken"],
    defaultSkillId: "skill-caramel-shuriken",
    packId: "core",
  },
  {
    id: "hero-star-wizard",
    name: "星星魔法師",
    avatar: "hero-star-wizard",
    price: 60,
    skillIds: ["skill-meteor-wish"],
    defaultSkillId: "skill-meteor-wish",
    packId: "core",
  },
  {
    id: "hero-robo-dog",
    name: "機器狗汪答",
    avatar: "hero-robo-dog",
    price: 50,
    skillIds: ["skill-rocket-punch"],
    defaultSkillId: "skill-rocket-punch",
    packId: "core",
  },
  {
    id: "hero-baby-dino",
    name: "恐龍寶貝噴噴",
    avatar: "hero-baby-dino",
    price: 45,
    skillIds: ["skill-bubble-breath"],
    defaultSkillId: "skill-bubble-breath",
    packId: "core",
  },
  {
    id: "hero-cat-hero",
    name: "貓咪超人喵俠",
    avatar: "hero-cat-hero",
    price: 70,
    skillIds: ["skill-paw-flurry"],
    defaultSkillId: "skill-paw-flurry",
    packId: "core",
  },
  // ---------- 英雄商店擴充包（見 MAPLE_UI_GUIDE.md）----------
  {
    id: "hero-yoru",
    name: "幽靈刺客小夜",
    avatar: "hero-yoru",
    price: 80,
    skillIds: ["skill-shadow-shred"],
    defaultSkillId: "skill-shadow-shred",
    packId: "core",
  },
  {
    id: "hero-panda",
    name: "熊貓拳聖胖達",
    avatar: "hero-panda",
    price: 55,
    skillIds: ["skill-bamboo-fists"],
    defaultSkillId: "skill-bamboo-fists",
    packId: "core",
  },
  {
    id: "hero-alice",
    name: "皇家琴劍士愛麗絲",
    avatar: "hero-alice",
    price: 90,
    skillIds: ["skill-symphony-blade"],
    defaultSkillId: "skill-symphony-blade",
    packId: "core",
  },
  {
    id: "hero-chiu",
    name: "爆彈科學家阿秋",
    avatar: "hero-chiu",
    price: 65,
    skillIds: ["skill-yuzu-cannon"],
    defaultSkillId: "skill-yuzu-cannon",
    packId: "core",
  },
  {
    id: "hero-kyle",
    name: "星海龍騎士凱爾",
    avatar: "hero-kyle",
    price: 100,
    skillIds: ["skill-star-dragon"],
    defaultSkillId: "skill-star-dragon",
    packId: "core",
  },
];
